<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>KroModIx.Plugin.Satisfactory</RootNamespace>
    <AssemblyName>KroModIx.Plugin.Satisfactory</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KroModIx.Plugin.Contracts"
                      PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Avalonia"
                      PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <None Update="plugin.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
